kind: Deployment
apiVersion: apps/v1
metadata:
  name: poly-volca-web
  namespace: openfaas-fn
  labels:
    app: poly-volca-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poly-volca-web
  template:
    metadata:
      labels:
        app: poly-volca-web
    spec:
      containers:
        - name: poly-volca-web
          image: rafaelpernil/poly-volca-web
          imagePullPolicy: Always
          serviceAccountName: custom-account
          automountServiceAccountToken: false
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 1Gi
              cpu: "500m"
            requests:
              memory: 1Gi
              cpu: "250m"
      restartPolicy: Always